import re

with open('app/src/main/java/com/example/data/repository/ChatRepository.kt', 'r') as f:
    lines = f.readlines()

new_lines = []
skip = False
for i, line in enumerate(lines):
    if "// 1. Automatic Model & Provider Routing" in line:
        new_lines.append(line)
        skip = True
        
        # Now append the new logic
        new_code = """        var actualModel = model
        var finalApiKey = ""

        if (actualModel.provider == ApiProvider.GOOGLE) {
            finalApiKey = googleKey
            if (!hasGoogle) throw Exception("Google Gemini API Key is missing. Please configure it in Settings.")
        } else {
            val providerKey = when (actualModel.provider) {
                ApiProvider.OPENAI -> settings.openaiApiKey
                ApiProvider.ANTHROPIC -> settings.anthropicApiKey
                ApiProvider.DEEPSEEK -> settings.deepseekApiKey
                else -> ""
            }
            if (providerKey.isNotEmpty()) {
                finalApiKey = providerKey
            } else if (hasGoogle) {
                // Auto-failover to Gemini if specific key is missing
                actualModel = AiModel.GEMINI_PRO
                finalApiKey = googleKey
            } else {
                throw Exception("API Key for ${actualModel.displayName} is missing. Please configure it in Settings.")
            }
        }

        // Retry mechanism
        val maxRetries = 3
        var currentTry = 0
        var success = false
        var responseText = ""
        var lastException: Exception? = null

        while (currentTry < maxRetries && !success) {
            try {
                when (actualModel.provider) {
                    ApiProvider.GOOGLE -> {
                        val geminiContents = mutableListOf<GeminiContent>()
                        history.forEach { msg ->
                            val parts = mutableListOf<GeminiPart>()
                            parts.add(GeminiPart(text = msg.content))
                            geminiContents.add(GeminiContent(role = if (msg.role == "user") "user" else "model", parts = parts))
                        }
                        val activeParts = mutableListOf<GeminiPart>()
                        if (attachedBase64Image != null) {
                            activeParts.add(GeminiPart(inlineData = GeminiInlineData("image/jpeg", attachedBase64Image)))
                        }
                        activeParts.add(GeminiPart(text = activePrompt))
                        geminiContents.add(GeminiContent(role = "user", parts = activeParts))

                        val req = GeminiRequest(
                            contents = geminiContents,
                            systemInstruction = GeminiContent(parts = listOf(GeminiPart(text = systemPrompt))),
                            generationConfig = GeminiGenerationConfig(temperature = 0.7f)
                        )
                        val response = NetworkClient.geminiService.generateContent(actualModel.id, finalApiKey, req)
                        responseText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                            ?: "No text response generated by Google Gemini."
                    }
                    ApiProvider.OPENAI, ApiProvider.DEEPSEEK -> {
                        val messages = mutableListOf<OpenAiMessage>()
                        messages.add(OpenAiMessage("system", systemPrompt))
                        history.forEach { msg ->
                            messages.add(OpenAiMessage(if (msg.role == "user") "user" else "assistant", msg.content))
                        }
                        messages.add(OpenAiMessage("user", activePrompt))
                        val req = OpenAiRequest(
                            model = actualModel.id,
                            messages = messages,
                            temperature = 0.7f
                        )
                        val authHeader = "Bearer $finalApiKey"
                        val service = if (actualModel.provider == ApiProvider.DEEPSEEK) NetworkClient.deepseekService else NetworkClient.openAiService
                        val response = service.generateCompletion(authHeader, req)
                        responseText = response.choices?.firstOrNull()?.message?.content ?: "No text response generated."
                    }
                    ApiProvider.ANTHROPIC -> {
                        val messages = mutableListOf<ClaudeMessage>()
                        history.forEach { msg ->
                            messages.add(ClaudeMessage(if (msg.role == "user") "user" else "assistant", msg.content))
                        }
                        messages.add(ClaudeMessage("user", activePrompt))
                        val req = ClaudeRequest(
                            model = actualModel.id,
                            messages = messages,
                            system = systemPrompt,
                            temperature = 0.7f
                        )
                        val response = NetworkClient.claudeService.generateMessage(apiKey = finalApiKey, request = req)
                        responseText = response.content?.firstOrNull()?.text ?: "No text response generated."
                    }
                }
                success = true
            } catch (e: Exception) {
                lastException = e
                currentTry++
                if (currentTry < maxRetries) {
                    kotlinx.coroutines.delay(1000L * currentTry) // Exponential backoff
                }
            }
        }

        if (!success) {
            throw Exception(lastException?.localizedMessage ?: "Failed to connect to AI provider after $maxRetries attempts.")
        }

        emit(responseText)

    }.flowOn(Dispatchers.IO)
"""
        new_lines.append(new_code)
        continue
        
    if skip and "suspend fun generateAiImage(prompt: String): String =" in line:
        skip = False
        # Remove getSimulatedResponse from the lines completely
        
    if not skip:
        new_lines.append(line)

with open('app/src/main/java/com/example/data/repository/ChatRepository.kt', 'w') as f:
    f.writelines(new_lines)

